### ISSUE TITLE
Set `HTTP_ACCEPT` in `jsonapi_headers`

### ISSUE THREAD

**Issue by wagenet** [graphiti-api/graphiti_spec_helpers#8]
https://github.com/graphiti-api/graphiti_spec_helpers/blob/master/lib/graphiti_spec_helpers/helpers.rb#L46

Without setting `HTTP_ACCEPT` Rails doesn't get the response format correct.

**Comment by richmolj** [comment]
Good addition, addresses an issue when Rails apps are not in "api only" mode.

Released in `1.0.1` - thanks @wagenet!
